/*
 * This Java source file was generated by the Gradle 'init' task.
 *//*
package database;

import org.flywaydb.core.Flyway;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ResourceBundle;

public class DatabaseInitService {
*//*    private final ResourceBundle resourceBundle = ResourceBundle.getBundle("database");
    private static final String JDBC_URL = "jdbcURL";


    public void databaseInit() throws SQLException {
        Flyway flyway = Flyway
                .configure()
                .dataSource(resourceBundle.getString(JDBC_URL), null, null)
                .load();
        flyway.migrate();*//*
    }

}*/
